version: '3.8'

services:
  filtergosha:
    build: .
    container_name: filtergosha
    restart: always
    ports:
      - "8787:8787"   # پنل وب و ترافیک VLESS (WebSocket, gRPC, XHTTP)
      - "1081:1081"   # پروکسی SOCKS5
    environment:
      - PORT=8787
      - SOCKS5_PORT=1081
      - DATA_DIR=/data
      - ADMIN_PASSWORD=FilterGosha   # رمز عبور ادمین
      # - RAILWAY_PUBLIC_DOMAIN=sub.yourdomain.com  # در صورت اتصال دامین
    volumes:
      - ./data:/data   # ذخیره دائمی دیتابیس، سکرت‌کی و مصرف‌ها
